In [1]:
import torch
import numpy as np

In [3]:
v = torch.tensor([1, 2, 3, 4, 5, 6])
print(v[1:])

tensor([2, 3, 4, 5, 6])


In [4]:
f = torch.FloatTensor([1, 2, 3, 4, 5, 6])
print(f.size())

torch.Size([6])


In [5]:
v.view(3, -1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [8]:
a = np.array([1, 2, 3, 4, 5])
tensor_cnv = torch.from_numpy(a)
print(tensor_cnv)
print(tensor_cnv.type())

tensor([1, 2, 3, 4, 5], dtype=torch.int32)
torch.IntTensor


In [9]:
numpy_cnv = tensor_cnv.numpy()
print(numpy_cnv)

[1 2 3 4 5]
